import os
import io
from main import app, db_session
from models import quotation, quotationItem, Invoice, InvoiceItem, Customer, Inventory
from datetime import datetime

def test_pdf_generation():
    with app.app_context():
        # Find or create a test customer
        customer = db_session.query(Customer).first()
        if not customer:
            customer = Customer(identification_number="TEST001", name="Test", surname="User")
            db_session.add(customer)
            db_session.commit()

        # Create a test quotation with long description
        q = quotation(customer_id=customer.identification_number, total_amount=100.0)
        db_session.add(q)
        db_session.flush()

        qi = quotationItem(
            quotation_id=q.id,
            quantity=1,
            unit_price=100.0,
            description="This is a very very long description that should wrap into multiple lines in the PDF generated by reportlab to prevent it from overlapping with the total amount column." * 5,
            item_code="LONGCODE"
        )
        db_session.add(qi)
        db_session.commit()

        print(f"Testing PDF generation for Quotation #{q.id}...")
        try:
            from main import generate_quotation_pdf
            # Simulate the request but call the function directly
            with app.test_request_context():
                response = generate_quotation_pdf(q.id)
                print(f"Quotation PDF generated successfully (Type: {type(response)})")
        except Exception as e:
            print(f"Quotation PDF generation FAILED: {e}")

        # Create a test invoice
        inv = Invoice(customer_id=customer.identification_number, total_amount=50.0, balance_due=50.0)
        db_session.add(inv)
        db_session.flush()

        ii = InvoiceItem(
            invoice_id=inv.id,
            quantity=1,
            unit_price=50.0,
            amount=50.0,
            description="Another very long description for an invoice item to ensure that the Paragraph wrapping works correctly here as well." * 5,
            item_code="INV-LONG"
        )
        db_session.add(ii)
        db_session.commit()

        print(f"Testing PDF generation for Invoice #{inv.id}...")
        try:
            from main import generate_invoice_pdf
            with app.test_request_context():
                response = generate_invoice_pdf(inv.id)
                print(f"Invoice PDF generated successfully (Type: {type(response)})")
        except Exception as e:
            print(f"Invoice PDF generation FAILED: {e}")

if __name__ == "__main__":
    test_pdf_generation()
